language: python
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=pypy3
install:
  - "pip install paramiko>=1.13.0 hostlists>=0.6.9 ."
script:
  - tox
branches:
  only:
    - master