language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - "pip install ."
  - "pip install -r requirements.txt"
script:
  - python tests/command_list_test.py
  - python tests/module_test.py
branches:
  only:
    - master